- name: check packages for updates
  shell: yum list updates | awk 'f;/Updated Packages/{f=1;}' | awk '{ print $1 }'
  changed_when: updates.stdout_lines | length > 0
  args:
    warn: false
  register: updates

- name: display count
  debug:
    msg: "Found {{ updates.stdout_lines | length }} packages to be updated:\n\n{{ updates.stdout }}"

- name: update the system
  yum:
    name: "*"
    state: latest
    exclude: "{{ excluded_packages }}"

- name: check if reboot is required
  shell: needs-restarting -r
  failed_when: false
  register: reboot_required
  changed_when: false

- name: display reboot info
  debug:
    msg: "{{ reboot_required.stdout }}"

- name: reboot the system
  reboot:
  when: updates.stdout_lines | length > 0 and reboot_required.rc != 0
