- name: Enable Windows Updates
  win_service:
    name: wuauserv
    start_mode: auto
    state: started

- name: Search and download Windows updates without installing them
  win_updates:
    state: searched
    register: result

- name: Check if reboot penging.
  win_dsc:
    resource_name: xPendingReboot
    Name: "{{ ansible_hostname }}"
  register: reboot_pending
  tags:
    - mssql_update

- name: Reboot
  win_reboot:
    reboot_timeout: 3600
  when: reboot_pending.reboot_required

- name: Install all security, critical, and rollup updates
  win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    reboot: yes
    reboot_timeout: 3600
  ignore_errors: True
  tags:
    - winupdate

- name: Check if reboot penging.
  win_dsc:
    resource_name: xPendingReboot
    Name: "{{ ansible_hostname }}"
  register: reboot_pending_after
  tags:
    - mssql_update

- name: Reboot
  win_reboot:
    reboot_timeout: 3600
  when: reboot_pending_after.reboot_required

- name: GPO force update
  win_shell: |
    gpupdate /force